### ISSUE TITLE
Release apk

### ISSUE THREAD

**Issue by dimalit** [cs8425/msp-controller#1]
Hi! Why wouldn't you release a pre-built .apk?

**Comment by cs8425** [comment]
Because I thought I might change code only if I needed.
There are no release version or some similar.
But if you still need pre-built .apk, I can upload it.

**Comment by dimalit** [comment]
Personally I have already build it :) But it took some time, so I think you can save someone's time in the future by uploading the apk!
P.S. I can send you the one that I've built (if you don't have it right on hand).
